### ISSUE TITLE
Feature request/proposition

### ISSUE THREAD

**Issue by Vagahbond** [RGBCube/ThemeNix#1]
Following our discussion on Discord I'm going to detail my thought here:

It would be great to have a way to define an accent color (optional) for each color scheme. 

My wish is to have a uniform naming scheme for each color scheme, so that I can just change the theme I use and the calls to colors will still be valid everywhere. 

I thought about something like that  : 
```nix
let
  myTheme = themes.custom {
    name   = "My Awesome Theme";
    author = "RGBCube";
    base00 = mkAccent "000000";    
    # ...
  };
```
or :
```nix
let
  myTheme = themes.custom {
    name   = "My Awesome Theme";
    author = "RGBCube";
    base00 = mkAllias "accent" "000000";    
    # ...
  };
```

So then I can do : 
```nix
            programs.kitty.settings = with theme.withHashtag; {
              color0  = accent;
            }
``` 

Maybe extend functionality so that I can use a pre-made color theme with my own aliases, so that I don't have to change every call to the theme manager whenever I wanna change the theme:
```nix
theme = themes mkAliasedTheme tango {
  background = "base00";
  accent= "base0F";
};
```

I hope I'm being clear ! 

If you don't want to implement it but appreciate the idea I could make a PR for it One Day:tm:

**Comment by RGBCube** [comment]
Done! this was also possible, since I don't check the theme values, only remove name and author to add the prefixes.

I've exposed the raw themes to do this. Check the readme after you've updated your flake input.
