### ISSUE TITLE
Wallpaper Hooks

### ISSUE THREAD

**Issue by orhnk** [RGBCube/ThemeNix#2]
Changing the colors is cool, but It's not sufficient for a complete "theme manager"
adding a possible option for wallpapers would be really cool!

```nix
let
  myTheme = themes.custom {
    name   = "My Awesome Theme";
    author = "RGBCube";
    base00 = "000000";
    # ...
    wallpapers = [
        "MyCustomTheme/" # / postfix indicates a directory of wallpapers
        "cool-wallpaper.png" # file
    ]
  };
in {}
```

And you can expose some functions API functions for:

- Querying currently selected wallpaper
- Calling a custom function to change the wallpaper.
- Some built-in functions to change the wallpaper:
      - Change the wallpaper in a period of time. (maybe the user can supply a custom wallpaper selector algorithm e.g random, respectfully etc.)

## Challenges

Changing the wallpaper is not straight forward. It *depends*.

For window systems like X you can supply some popular options built-in:

```nix
# ThemeNix initialization config:
backend = "feh"; # xsetroot, hsetroot
```

And for those who uses a tool that is not built-in (PR it btw)

```nix
# ThemeNix initialization config:
# %s represents the wallpaper path here. You may find a better solution (like exposing the following wallpaper to the API)
script = ''
feh --bg-fill %s
''
```

**Comment by RGBCube** [comment]
No, I will just add a helper function that generates a theme from a wallpaper. What you're describing isn't a """hook""" either.

This is how it will look like:

```nix
let
  myTheme = themes.fromImage ./wallpaper.png;
in {};
```

ThemeNix will ***never ever*** modify your configuration. It's up to you to set your wallpaper. Even if it were to, the solution you are describing is bad, since we could write modules that automatically enable if a specific module is enabled. Please learn Nix.

**Comment by orhnk** [comment]
https://stackoverflow.com/questions/467557/what-is-meant-by-the-term-hook-in-programming

also read my post before answering.

**Comment by RGBCube** [comment]
This literally isn't a hook. There is no event here. It is just a variable defined somewhere, and yes, I've read your post.

**Comment by RGBCube** [comment]
Since ThemeNix doesn't any value other than valid colors, you can do this:

```nix
theme = themes.custom (themes.raw.gruvbox-dark-hard // {
  corner-radius = 16;
  border-width  = 3;

  font.size.normal = 12;
  font.size.big    = 18;

  font.sans.name    = "Lexend";
  font.sans.package = pkgs.lexend;

  font.mono.name    = "RobotoMono";
  font.mono.package = (pkgs.nerdfonts.override {
    fonts = [
      "RobotoMono"
    ];
  });
```

(taken from my config)

and use them whereever
